### ISSUE TITLE
Cura 5

### ISSUE THREAD

**Issue by mtongnz** [ronoaldo/FlashforgeFinderIntegration#13]
Do you plan to make this available for Cura 5?

**Comment by ronoaldo** [comment]
Hi! Yes, I plan to support the newer version, but I have limited time. I'll
take a look at the API changes for both my plugins.

In the meantime, I kindly suggest sticking with Cura 4.

If you have the time I can review any pull requests. Since I don't remember
to use much UI code, porting to the new version should not require too much
effort.

I'll try to add some test cases, build scripts and GitHub Actions to help
the process.

Thanks!

Em sáb., 7 de mai. de 2022 23:27, Matt ***@***.***> escreveu:

**Comment by mtongnz** [comment]
Great :)

I've managed to get it mostly working in Cura 5.  I haven't tested in older versions.  And the grayscale image conversion doesn't seem to want to work.

So it's not really ready to merge but is there so hopefully my fork will be of assistance.

**Comment by jcbelanger** [comment]
Just an FYI to others who can't wait.  I added support for Cura 5 with pull request https://github.com/ronoaldo/FlashforgeFinderIntegration/pull/15

**Comment by ronoaldo** [comment]
Thanks to @jcbelanger - this is now suported! I'll upload to Marketplace in the next few days.

**Comment by ronoaldo** [comment]
Uploaded to Marketplace - should be reviewed and tested by Cura team soon!
